# Basic
# Some long strings (file path, e.g.) just do not fit in a line with 80 width.
# And if break them to a width 80 - it just looks ugly.
# However, it is still better to follow the width 80 standard.
printWidth: 120
tabWidth: 4
useTabs: false
singleQuote: false
semi: true
bracketSpacing: false
arrowParens: "always"

# Extra
trailingComma: "none"
jsxBracketSameLine: false
parser: "babylon"
requirePragma: false
insertPragma: false
proseWrap: "preserve"

overrides:
    - files: ["*.js"]
      options:
        singleQuote: true

    - files: ["*.pug", "*.scss", "*.md"]
      options:
        tabWidth: 2
