# Basic
#printWidth: 120
tabWidth: 4
useTabs: false
singleQuote: false
semi: true
bracketSpacing: false
arrowParens: "always"

# Extra
trailingComma: "none"
jsxBracketSameLine: false
parser: "babylon"
requirePragma: false
insertPragma: false
proseWrap: "preserve"

overrides:
    - files: ["*.pug", "*.scss"]
      options:
        tabWidth: 2
